### ISSUE TITLE
Display potential appearances candidates with buzzsumo backlinks in a new verdict tab 'candidates' (like verdicts/AE/candidates)

### ISSUE THREAD

**Issue by Ledoux** [feedback-news/feedback-main#133]
See https://docs.google.com/presentation/d/1kBcb9s_YZGT0XLjDa1X89-4_X7Lmxi63OhyZ1-qhXAU/edit#slide=id.g92288e2265_1_202 page 13

**Comment by mathieuabeille** [comment]
Regarding this issue, maybe I should be include in the discussion.

I was seeing something like this.
![potentialLinks](https://user-images.githubusercontent.com/29702932/97709579-dbdf0f00-1aba-11eb-8ffe-17f46d82bc1e.png)
![potentialAppearance](https://user-images.githubusercontent.com/29702932/97709595-e26d8680-1aba-11eb-8d4f-d72bc03b150e.png)

Add a tab potential appearance instead of the button backlinks of this appearance. And a form for validating this potential appearance.

I have divided this into three user stories:
Step 1: https://www.notion.so/User-Story-Potential-links-tabs-bcaffbdce24b494eb70fdb7e5d9c7d27
Step 2: https://www.notion.so/User-Story-Links-flagged-on-Facebook-Status-7313e87c65a54ab5988fd2fd3884fa1a
Step 3: https://www.notion.so/User-Story-Potential-Appearance-Review-Form-74b81ac464054bf2917e35457b874bc1

What do you think? @tdquan @Ledoux

**Comment by mathieuabeille** [comment]
I am closing that issue. It is not a priority anymore. I will open a brand new ticket when we will want to fetch backlinks from Google or Buzzsumo API 
@tdquan @Ledoux @emvincent
